### ISSUE TITLE
App crash after pressing on action button

### ISSUE THREAD

**Issue by yshahak** [noinskit/flutter_local_notifications#5]
I managed to create buttons according to the sample. However, when a action button getting pressed, the app crash inside `NotificationActionReceiver`:
```
E/AndroidRuntime(17591): java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.NotificationActionReceiver: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
E/AndroidRuntime(17591): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
E/AndroidRuntime(17591): 	at android.app.ActivityThread.access$1400(ActivityThread.java:219)
E/AndroidRuntime(17591): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
E/AndroidRuntime(17591): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(17591): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(17591): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(17591): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17591): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(17591): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(17591): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
E/AndroidRuntime(17591): 	at com.dexterous.flutterlocalnotifications.NotificationActionReceiver.onReceive(NotificationActionReceiver.java:68)
```

I added the `receiver` in the `Manifest` so I have no idea what is cause for the crash..

**Comment by yshahak** [comment]
OK, I wasn't aware to the fact that you need to extend `Application` on android and call:
```java
FlutterLocalNotificationsPlugin.setPluginRegistrant(this);
```

**Comment by noinskit** [comment]
Cool, I'm happy to see that the problem is resolved!
